Add WalletPicker component for connecting to multiple blockchain networks and wallets
aleph-im/front-aleph-core pull request #16
Opened 2023-03-28 10:08 UTC by leirbag95

This pull request adds a new component, WalletPicker, to allow users to easily connect their wallets to various blockchain networks and choose their preferred wallet provider.

The **WalletPicker** component provides a user-friendly interface with networks menus to select the blockchain network and then wallet provider. Users can select from a range of popular wallet providers such as Metamask, Phantom, or even Polka.js. 

This component is designed to be highly customizable, and can be easily integrated into existing applications. It provides a simple and streamlined way for users to connect to their preferred wallets on their preferred blockchain networks.

<img width="398" alt="Capture d’écran 2023-03-28 à 12 08 10" src="https://user-images.githubusercontent.com/17054452/228203278-2008741f-72f9-42ad-b86e-4411cf956079.png">

2023-03-28 11:21 UTC, BjrInt requested changes
Can you also provide a working example with an actual provider (ex: instanciating Metamask once the button is clicked?)

2023-03-28 11:21 UTC, BjrInt commented on src/components/WalletPicker/cmp.tsx
> +  networks = [],
These are not defined in the `types.ts` file. Can you :
- Create a type definition for the `network` object
- Remove unused props (ex: color, kind, variant)

2023-03-28 11:21 UTC, BjrInt commented on src/components/WalletPicker/cmp.stories.tsx
> +    callback: null
If callback is supposed to be a function provide a noop `() => null` as a default value instead (so you don't run into a `TypeError`)

2023-03-28 11:21 UTC, BjrInt commented on src/components/WalletPicker/types.ts
> +  className?: string
Why is there a className property?

2023-03-30 12:36 UTC, leirbag95 commented on src/components/index.ts
> +export { default as WalletPicker } from './WalletPicker'
Done, I pull and rebase main branch into Feat/WalletPicker branch

2023-03-30 12:37 UTC, leirbag95 commented on src/components/WalletPicker/cmp.tsx
> +              networks.map((network) => (
Now, NetworkProps has been created 👍

2023-03-30 12:37 UTC, leirbag95 commented on src/components/WalletPicker/types.ts
> +  size: PickerSize
I added another kind of size : 'large' with bigger text, width and icon

2023-03-31 09:47 UTC, leirbag95 commented on src/components/WalletPicker/cmp.stories.tsx
> +    callback: null
This example does not exist anymore

2023-03-31 09:47 UTC, leirbag95 commented on src/components/WalletPicker/cmp.stories.tsx
> +  color: 'main2',
replaced it by backgroundColor

2023-03-31 09:48 UTC, leirbag95 commented on src/components/WalletPicker/cmp.tsx
> +  networks = [],
NetworkProps and WalletProps has been created

2023-04-20 08:50 UTC, closed without merging