New component: TextAction
aleph-im/front-aleph-core pull request #19
Opened 2023-04-27 08:34 UTC by leirbag95

This pull request adds a new component called **TextAction**, which allows the user to create a text with an action next to it. This component is useful when you want to display a text and provide an action that the user can take related to the text.
You can provide the `action` prop which is used to specify the action to be taken when the user clicks on the action button.

I have tested the TextAction component locally and it works as expected with Copy to Clipboard function. 

Please review and let me know if you have any feedback or suggestions for improvements.

![image](https://user-images.githubusercontent.com/17054452/234806511-47d8941b-0336-4e7b-a7cb-4ed50eb396eb.png)

2023-05-03 10:44 UTC, BjrInt requested changes
Hey,

Thanks for the PR. 
Can you please keep this component minimal, just the text, the icon, and a callback as a prop. There is some unecessary bloat (that's also causing type errors) that could easily be fixed by trimming the code. 

TL;DR: Just keep this (without title, align, type, ...) 
![image](https://user-images.githubusercontent.com/26065817/235895049-4c6f7be1-fd97-44b1-9af6-ea02cdc9494f.png)

2023-05-03 10:44 UTC, BjrInt commented on src/components/TextAction/cmp.tsx
> +        >
This is not needed, keep it simple :wink:

2023-05-03 10:44 UTC, BjrInt commented on src/components/TextAction/types.ts
> +}
You can remove this also.

2023-05-03 10:44 UTC, BjrInt commented on src/components/TextAction/cmp.tsx
> +  const [, copyToClipboard] = useClipboard(content)
Thanks for creating the hook, but since this is intended as a generic component, could you allow to pass any function as a callback prop, instead of calling this by default ?

2023-05-03 10:44 UTC, BjrInt commented on src/components/TextAction/cmp.tsx
> +      }}
This returns a Typescript error since StyledTextAction requires several other props.

2023-05-03 10:44 UTC, BjrInt commented on src/components/TextAction/cmp.tsx
> +  const [iconName, setIconName] = useState<string>(icon)
iconName is not a string (please import the type from FontAwesome)

2023-05-03 10:44 UTC, BjrInt commented on src/components/TextAction/cmp.tsx
> +                    ...transitionStyles[state],
You cannot use a generic string or number to access the key of an object (maybe a keyof type would help here?)

2023-05-04 10:03 UTC, leirbag95 commented
> Hey,
> 
> Thanks for the PR. Can you please keep this component minimal, just the text, the icon, and a callback as a prop. There is some unecessary bloat (that's also causing type errors) that could easily be fixed by trimming the code.
> 
> TL;DR: Just keep this (without title, align, type, ...) ![image](https://user-images.githubusercontent.com/26065817/235895049-4c6f7be1-fd97-44b1-9af6-ea02cdc9494f.png)

Ok I'm going to fix it today

2023-05-30 06:36 UTC, BjrInt approved these changes

2023-05-30 06:36 UTC, merged